### ISSUE TITLE
Missing file core.post_calibration

### ISSUE THREAD

**Issue by Ma-Zijing** [Dirtyboy1029/MALCERTAIN#2]
Hi! In the tools.py you use the core.post_calibration package, however, there does not exist this file. Could you please tell us where to find the file? Thank you.

**Comment by Dirtyboy1029** [comment]
Thank you for your question. Post calibration is an uncertainty calibration method and is not within the scope of discussion in this paper.

**Comment by Ma-Zijing** [comment]
Got it. I just delete it. Thanks
